<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBTimesheetApp/TimesheetGenesis/dbCreateTimesheet" name="dbCreateTimesheet-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbCreateTimesheet.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBTimesheetApp/TimesheetGenesis/dbCreateTimesheet"/>
    <wsdl:binding name="dbCreateTimesheet_ptt-binding" type="dbc:dbCreateTimesheet_ptt" xmlns:dbc="http://xmlns.oracle.com/pcbpel/adapter/db/SBTimesheetApp/TimesheetGenesis/dbCreateTimesheet">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>