<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBTimesheetApp/TimesheetOverview/QTimeDB" name="QTimeDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QTimeDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBTimesheetApp/TimesheetOverview/QTimeDB"/>
    <wsdl:binding name="QTimeDB_ptt-binding" type="qtim:QTimeDB_ptt" xmlns:qtim="http://xmlns.oracle.com/pcbpel/adapter/db/SBTimesheetApp/TimesheetOverview/QTimeDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QTimeDBSelect">
            <soap:operation soapAction="QTimeDBSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>